version: "3.8"
services:
  postgres_cadastro:
    container_name: postgres_cadastro_aifude
    image: postgres:latest
    environment:
      POSTGRES_USER: cadastro
      POSTGRES_PASSWORD: cadastro
    ports:
      - 5432:5432